added center of mass to Panda DH definition (and cleaned it up a bit)
petercorke/robotics-toolbox-python pull request #304
Opened 2022-04-12 10:09 UTC by jenskober

In pull request #294 some of the inertia parameters were ported from the matlab version. The center of mass for the links was still missing (without which dynamics calculations will be wrong). I've added them here and also cleaned up the white space a bit.

2022-06-01 11:05 UTC, AunSiro requested changes
I was about to suggest the same thing. However, it must be noted that the parameters come from https://github.com/marcocognetti/FrankaEmikaPandaDynModel which uses the axes as in https://frankaemika.github.io/docs/control_parameters.html, but the model here ignores the (7) axes and links the last solid to the (F) axes. Therefore, the center of mass of the last solid must be given in (F) coordinates.

2022-06-01 11:05 UTC, AunSiro commented on roboticstoolbox/models/DH/Panda.py
> +                r=[1.0517e-02, -4.252e-03, 6.1597e-02],
```suggestion
                r=[1.0517e-02, -4.252e-03, -4.5403e-02],
```
The center of mass of the last solid must be given in (f) coordinates.

2022-07-12 21:03 UTC, jenskober commented
@AunSiro Thanks! Indeed, both the marcocognetti and frankaemika DH definition include a static 8th joint for the flange, while here this is rolled into the 7th joint.

2022-07-13 16:12 UTC, jenskober commented
should now be compatible with the latest version in master

2023-02-04 10:21 UTC, JeanElsner commented
I too was about to suggest the same thing, before I saw your pull request. It would be great to see this merged!

2026-08-09 23:53 UTC, petercorke commented
Thank you for your interest in RTB, and for adding these — the centre-of-mass values for `models.DH.Panda()` were genuinely missing since #294 ported the mass/inertia-tensor parameters but not `r`, which makes dynamics calculations wrong for this model.

Your values just landed in #588, crediting this PR as the source. Closing as merged (via #588 rather than a direct merge of this PR, since it's since drifted from current `main`) — thank you for the contribution.

2026-08-09 23:53 UTC, closed without merging